name:                pptxCountSlides
version:             0.1.0.0
github:              "pierrezolghadri/pptxCountSlides"
license:             MIT
author:              "Pierre Zolghadri"
copyright:           "2023 Pierre Zolghadri"

dependencies:
- base >= 4.7 && < 5
- zip-archive
- directory
- bytestring
- containers

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

executables:
  pptxCountSlides-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pptxCountSlides